spring.application.name: ratings-data-service

spring:
  cloud:
    config:
      uri: http://localhost:${config.port:8888}
      discovery:
        enabled: true
        service-id: configuration-server



