server.port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rattings-data?serverTimeZone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  flyway:
    url: jdbc:mysql://localhost:3306/rattings-data?serverTimeZone=UTC
    schemas: rattings-data
    user: root
    password: root

management:
  endpoints:
    web:
      exposure:
        include: "*"